spring:
  application:
    name: graph-service
  banner:
    location: classpath:banner.txt

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

server:
  port: 9002
