#spring:
#  application:
#    name: connection-service
#
#  banner:
#    location: classpath:banner.txt
#    
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/connection_db
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
##graph:
##  service:
##     url :  http://GRAPH-SERVICE/api/v0/graph/sync
#
#server:
#  port : 9001



spring:
  application:
    name: connection-service

  banner:
    location: classpath:banner.txt

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:9001}

eureka:
  client:
    service-url:
      defaultZone: https://social-graph-exployer-backend-eureka.onrender.com/eureka/
